### ISSUE TITLE
Dot completion

### ISSUE THREAD

**Issue by ishanray** [wy-z/Golite#15]
Hi,

Is it possible to provide dot completion automatically in this package? Also method signatures if possible.

Thanks

**Comment by wy-z** [comment]
Hi,

Code completion is provided by `gocode`, and it is enabled with [`inhibit_word_completions`](https://www.sublimetext.com/docs/3/api_reference.html) by default~
If you want to enable `word_completions`, you can set `gocode_inhibit_word_completions` to `false`, see https://github.com/wy-z/Golite/blob/master/Golite.sublime-settings#L9~

Looking forward to your feedback~
Thanks
